require 'coffee_script'
require 'spree_core'
require 'spree_multi_currency/engine'
require 'spree_multi_currency/version'
require 'spree_multi_currency/currency_converter'
require 'spree_multi_currency/get_rates'
require 'spree_multi_currency/round_price'
